### ISSUE TITLE
Firefox 59: Add to (Semantic)Scuttle popup is immediately closed

### ISSUE THREAD

**Issue by nathan-sain** [FrenchHope/Add-to-Semantic-Scuttle-WebExt#1]
Add to (Semantic)Scuttle popup triggers an error and the popup is immediately closed
The console shows the error: `Error: Opener tab must be in the same window as the tab being created`

**Comment by FrenchHope** [comment]
I think it is not compatible with another extension, could you try with another Firefox profile ?

**Comment by nathan-sain** [comment]
You're right, thanks for the guidance. I was using the Conex extension and the latest edition is not compatible with this Semantic Scuttle extension.
